#ifndef VI_INTERNAL_TYPES_HPP_EXTENDED
#define VI_INTERNAL_TYPES_HPP_EXTENDED
#include <vitex/internal/types.hpp>
#define TYPENAME_VERTEX "vertex"
#define TYPENAME_ELEMENTVERTEX "element_vertex"
#define TYPENAME_VECTOR3 "vector3"
#define TYPENAME_JOINT "joint"
#define TYPENAME_RECTANGLE "rectangle"
#define TYPENAME_VIEWPORT "viewport"
#define TYPENAME_ANIMATORKEY "animator_key"
#define TYPENAME_SKINANIMATORCLIP "skin_animator_clip"
#define TYPENAME_PHYSICSHULLSHAPE "physics_hull_shape"
#define TYPENAME_INPUTLAYOUTATTRIBUTE "input_layout_attribute"
#define TYPENAME_AUDIOCLIP "audio_clip"
#define TYPENAME_ELEMENTBUFFER "element_buffer"
#define TYPENAME_MESHBUFFER "mesh_buffer"
#define TYPENAME_SKINMESHBUFFER "skin_mesh_buffer"
#define TYPENAME_INSTANCEBUFFER "instance_buffer"
#define TYPENAME_TEXTURE2D "texture_2d"
#define TYPENAME_SHADER "shader"
#define TYPENAME_MODEL "model"
#define TYPENAME_SKINMODEL "skin_model"
#define TYPENAME_GRAPHICSDEVICE "graphics_device"
#define TYPENAME_SKINANIMATION "skin_animation"
#define TYPENAME_MATERIAL "material"
#define TYPENAME_COMPONENT "base_component"
#define TYPENAME_ENTITY "scene_entity"
#define TYPENAME_SCENEGRAPH "scene_graph"
#define TYPENAME_ELEMENTNODE "ui_element"
#endif