name: CMake
on: [push]
jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: docker build -f var/images/gcc.Dockerfile -t package:staging .